name: Depoly to R-Connect dev environment
on: push
jobs:
  DeployRConnectDev:
    environment: Test
    runs-on: shellai-runner-private-tst
    #container: ubuntu
    steps:
      - shell: bash
        run: sudo apt-get update && sudo apt-get install -y libssl-dev curl libcurl4-openssl-dev
      - uses: actions/setup-python@v2
      - uses: sede-open/r-lib-actions/setup-r@v2-branch
        with:
          r-version: 4.2.3
          use-public-rspm: true
      - uses: sede-open/rstudio-actions/setup-connect@main
      - uses: actions/checkout@v3

      - shell: bash
        run: cd src && Rscript -e 'rsconnect::writeManifest()'


      - uses: sede-open/rstudio-actions/connect-publish@main
        with:
          url: https://${{ secrets.CONNECT_API_KEY_DEV }}@${{ secrets.CONNECT_SERVER }}
          namespace: experimental-beta
          dir: ./src/:/shiny/app/path/
